# Generated by Django 4.1.4 on 2022-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarylinebot', '0002_diary_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
