# Generated by Django 4.1.4 on 2022-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarylinebot', '0003_alter_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
