# Generated by Django 4.1.4 on 2022-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarylinebot', '0004_alter_diary_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(),
        ),
    ]
