# Generated by Django 4.1.4 on 2022-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarylinebot', '0005_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
