# Generated by Django 4.1.4 on 2022-12-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarylinebot', '0006_diary_response_alter_diary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='diary',
            name='response',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
